version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/app.dockerfile
    image: crm_task_app
    volumes:
      - .:/var/www/html
      - ./docker/entrypoint.sh:/etc/entrypoint.sh
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/php:/usr/local/etc/php/conf.d
    ports:
      - 50:80
    working_dir: /var/www/html
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - ${MYSQL_FORWORD_PORT:-3306}:${MYSQL_PORT:-3306}
    volumes:
      - mysql_data:/var/lib/mysql
# Utility containers
  composer:
    image: composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: composer
    tty: true
    stdin_open: true
  symfony:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/app.dockerfile
    image: crm_task_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: symfony
    tty: true
    stdin_open: true
  console:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/app.dockerfile
    image: crm_task_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: php ./bin/console
    tty: true
    stdin_open: true
volumes:
  mysql_data: